let DATA = [
  {
    name: "Amirosein",
    id: 1,
    gender: "male",
    chats: [
      {
        id: 1,
        messege: "salam man amirhosein hastam",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 2,
        messege: "salam khoshbakhtam",
        isOpponent: true,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 3,
        messege: "dorod bar shoma",
        isOpponent: false,
        messegeTime: "18:24",
        replay: { text: "hello world", isOpponent: false, id: 1 },
        isforwarded: {},
      },
    ],
  },
  {
    name: "Alireza",
    id: 2,
    gender: "male",
    chats: [
      {
        id: 1,
        messege: "salam man alireza hastam",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 2,
        messege: "chekhabar",
        isOpponent: true,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 3,
        messege: "salamati",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
    ],
  },
  {
    name: "Elham",
    id: 3,
    gender: "female",
    chats: [
      {
        id: 1,
        messege: "salam man elham hastam",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 2,
        messege: "khob ke chi",
        isOpponent: true,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 3,
        messege: "pichpichi",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
    ],
  },
  {
    name: "Shokofeh",
    id: 4,
    gender: "female",
    chats: [
      {
        id: 1,
        messege: "salam bootcamper grami",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 2,
        messege: "dorod bar to",
        isOpponent: true,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 3,
        messege: "chikara mikoni?",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
    ],
  },
  {
    name: "Ahmad",
    id: 5,
    gender: "male",
    chats: [
      {
        id: 1,
        messege: "salam bar dustan",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 2,
        messege: "ishala hame salamat bashan",
        isOpponent: true,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
      {
        id: 3,
        messege: "hamchenin",
        isOpponent: false,
        messegeTime: "18:24",
        replay: {},
        isforwarded: {},
      },
    ],
  },
];

module.exports = DATA;
